name: Daily Job Search Emailer

on:
  schedule:
    - cron: '30 0 * * *'   # 6:00 AM IST
    - cron: '30 6 * * *'   # 12:00 PM IST
    - cron: '30 12 * * *'  # 6:00 PM IST
    - cron: '30 18 * * *'  # 12:00 AM IST
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      # 🚫 REMOVE setup-python completely

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run job search script
        env:
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
          EMAIL_RECEIVER: ${{ secrets.EMAIL_RECEIVER }}
        run: python job_search.py
